### ISSUE TITLE
dox-foundation --help (or any other invocation) fails with ENOENT

### ISSUE THREAD

**Issue by pcafstockf** [mattmcmanus/dox-foundation#1]
fs.js:338
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'views/template.jade'
    at Object.fs.openSync (fs.js:338:18)
    at Object.fs.readFileSync (fs.js:182:15)
    at Object.<anonymous> (node_modules/dox-foundation/lib/dox-foundation.js:7:20)
    at Module._compile (module.js:449:26)

**Comment by mattmcmanus** [comment]
Thanks for the report. I just pushed 0.2.0 out which fixes that error. If you could try that out and let me know if that fixes your problem that would be great.
